/**
 * observe — record a retrieval from wherever one actually happens.
 *
 * Deliberately NOT inside `retrieve`. That function is pure and synchronous,
 * it is called tens of thousands of times by the evaluation suites, and
 * recording there would both slow them down and fill the ledger with the very
 * queries the suites score — the contamination that emptied the first backfill.
 *
 * Recording belongs at the EDGES: the command line, and any tool an agent
 * holds. Those are the places where a real person or a real agent asked a real
 * question, which is the only traffic worth learning from.
 */
import { record, type RetrievalRecord } from './ledger';
import type { Hit } from './retrieval';
import { redactForLedger } from './safety';

/**
 * Who is asking and in what run. Both come from the environment so a host can
 * set them once; both are optional, because a ledger that refuses to write
 * without perfect provenance writes nothing.
 */
export function who(): { by: string; session: string } {
  return {
    by: process.env.CAIRN_AGENT ?? 'cli',
    session: process.env.CAIRN_SESSION ?? 'adhoc',
  };
}

/**
 * `ctx` names the session and agent explicitly. A stdio process serves one
 * session and reads them from the environment; a hosted gateway serves many
 * from one process, and the environment cannot tell them apart.
 */
export function observe(query: string, hits: Hit[], source: string, ctx: { by?: string; session?: string } = {}): void {
  if (!query.trim()) return;
  /*
   * Measurement runs do not count as usage.
   *
   * The eval suites replay the same eight scenarios thirty times each, through
   * the same code path a person uses, and every row landed in the committed
   * ledger tagged `cli:find` -- indistinguishable from somebody actually
   * asking. 240 of 273 rows were the test suite. `cairn:status` reported them
   * as adoption, which made the only evidence of use in this project a thing
   * the project generated by testing itself.
   *
   * An instrument that records its own calibration runs as observations is
   * the failure this corpus exists to catch, and it shipped here.
   */
  if (process.env.CAIRN_EVAL) return;
  const env = who();
  const by = ctx.by ?? env.by;
  const session = ctx.session ?? env.session;
  /*
   * Redacted before it is written, because the ledger is committed.
   *
   * The whole point of this corpus is that people paste the error they
   * actually got, and an error is the least sanitised text in software: it
   * carries tokens, home paths, hostnames, and — in the environment this is
   * about to be used in — record ids, org ids and email addresses out of an
   * MCP tool's failure response. `record` refuses a submission carrying those
   * and the ledger wrote them verbatim, so the safer-looking path was the
   * leaking one.
   *
   * Redact rather than refuse: a query that cannot be logged is still a query
   * worth measuring, and dropping it silently would bias the delivery numbers
   * toward the queries that happen to be clean.
   */
  const { text: safeQuery } = redactForLedger(query);
  const returned = hits.slice(0, 5).map((h, i) => ({
    id: h.finding.id,
    rank: i + 1,
    strength: h.strength,
  }));
  const outcomes: RetrievalRecord['outcomes'] = {};
  for (const r of returned) outcomes[r.id] = r.rank === 1 ? 'surfaced' : 'served';
  record({ at: new Date().toISOString(), by, session, query: safeQuery, returned, source, outcomes });
}
